project:
  type: book
  resources: 
    - Images/**
   # - Data/**

book:
  title: "Pmetrics in R"
  author: "Michael Neely"
  date: "July 20, 2026"
  chapters:
    - index.qmd
    - intro.qmd
    - overview.qmd
    - workflow.qmd
    - data.qmd
    - models.qmd
    - NPAG.qmd
    - objects.qmd
    - examine.qmd
    - NPAG_cov.qmd
    - simulation.qmd
    - PTA.qmd
    #- Validate.qmd
    - plotly.qmd
    - Compare.qmd
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    title: Sections

bibliography: Extras/references.bib

format:
  html:
    theme: cosmo
    css: Extras/custom.scss
    include-in-header: Extras/copy-all-code.html
    toc: true
    toc-title: "On this page" 
    link-external-newwindow: true
    embed-resources: false

pdf:
    documentclass: scrreprt



